<?xml version="1.0" encoding="utf-8"?><Database Name="TestNV" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ERP-KHANHHL;Initial Catalog=TestNV;Integrated Security=True" SettingsObjectName="Server____NV.Properties.Settings" SettingsPropertyName="TestNVConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Person" Member="Persons">
    <Type Name="Person">
      <Column Name="MaNV" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="Ho" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IrisCode" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>